sudo: required
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="COMPILER=g++-9 && CXX=g++-9 && CXX_STANDARD=17"
      addons:
        apt:
          packages: libcrypto++-dev g++-9
          sources: &sources
            - ubuntu-toolchain-r-test

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - mkdir -p build && cd build
  - cmake -DCMAKE_CXX_COMPILER=${COMPILER} -DCXX_STANDARD=${CXX_STANDARD} -DBUILD_CPR_TESTS=false ..
  - make
